<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <LangVersion>12</LangVersion>
      
    <!-- NuGet Package Information -->
    <PackageId>FauFau</PackageId>
    <Authors>TheMeldingWars</Authors>
    <Description>FauFau is a library for manipulating FireFall's various file formats and protocols</Description>
    <PackageVersion>1.5.3</PackageVersion>
    <AssemblyVersion>1.5.3</AssemblyVersion>
    <Version>1.5.3</Version>
    <FileVersion>1.5.3</FileVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/themeldingwars/FauFau</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>false</Optimize>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>false</Optimize>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>false</Optimize>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="[10.0.11,)" />
    <PackageReference Include="SharpCompress" Version="[0.50.4,)" />
    <PackageReference Include="TMW.Bitter" Version="[1.0.0,)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
