name: Build and publish

on:
  push:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_DIRECTORY: ${{ github.workspace }}/nuget

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux, os: ubuntu-24.04 }
        - { name: Windows, os: windows-2025-vs2026 }
        - { name: macOS, os: macos-26 }
        dotnet:
        - { name: .NET 8, version: '8.0.x' }
        - { name: .NET 10, version: '10.0.x' }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: 'recursive'
            
      - name: Setup ${{ matrix.dotnet.name }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        env:
          DOTNET_VERSION: ${{ steps.setup-dotnet.outputs.dotnet-version }}
        run: dotnet new globaljson --sdk-version $env:DOTNET_VERSION --force
      - name: Verify SDK Installation
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Create NuGet package
        run: dotnet pack -c Release FauFau/FauFau.csproj --output $NUGET_DIRECTORY
      - name: Publish NuGet package as artifact
        if: matrix.platform.name == 'Linux' && matrix.dotnet.name == '.NET 8'
        uses: actions/upload-artifact@v7
        with:
          name: FauFau
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NUGET_DIRECTORY }}/*.*nupkg

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    needs: [ build ]
    permissions:
      id-token: write
 
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: FauFau
          path: ${{ env.NUGET_DIRECTORY }}
      - name: NuGet Login
        uses: NuGet/login@v1
        id: login
        with:
          user: TMW
      - name: Publish FauFau NuGet
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
        run: dotnet nuget push $NUGET_DIRECTORY/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
